### ISSUE TITLE
[Question] How are cache and error numbers generated? 

### ISSUE THREAD

**Issue by sirinath** [jk-jeon/fp#5]
How are the cache numbers ([this](https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/detail/dragonbox_cache.h#L38) and [this](https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/detail/dragonbox_cache.h#L151)) and error ([this](https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/detail/dragonbox_cache.h#L842)) numbers generated?

These numbers are different from what is found in the [dragonbox repo](https://github.com/jk-jeon/dragonbox/blob/master/include/dragonbox/dragonbox.h).

**Comment by jk-jeon** [comment]
Yes, the tables in this repo is a strict superset of that in the Dragonbox repo. The reason is because tables in this repo includes additional entries for the reverse (decimal-to-binary) conversion. (The tables in this repo is the union of the entries required for Dragonbox and the entries required for the reverse conversion.)

The source code for the table generation is in this directory: [https://github.com/jk-jeon/fp/tree/master/subproject/meta/source](https://github.com/jk-jeon/fp/tree/master/subproject/meta/source).

The code is somewhat non-intuitive, because it involves validity check of cache precision, which is explained in Section 6 of [this paper](https://github.com/jk-jeon/dragonbox/blob/master/other_files/Dragonbox.pdf) and Section 4 of [this paper](https://github.com/jk-jeon/Grisu-Exact/blob/master/other_files/Grisu-Exact.pdf). It would be very hard to read the code without a fair amount of understanding of the background theory. But I believe it may continue to work also for different formats you probably have in mind with only some minor corrections.

**Comment by sirinath** [comment]
Since there ha been some commits to both `dragonbox` and `fp` with fixes, are the 2 repos now consistent with each other?

Also there has hardly been any improvements to either algorithms lately.

**Comment by jk-jeon** [comment]
The fix in the dragonbox repo should be ported here as well. But I expected to get some feedback on https://github.com/jk-jeon/dragonbox/issues/11#issuecomment-757035179, so I decided to do the patch after updating the code according to the feedback. So far, it seems nobody has been interested in giving some feedback on that...

**Comment by sirinath** [comment]
Also the implementations of policies in both the repos are complicated. Perhaps it can be simplified to be simple.

**Comment by sirinath** [comment]
Ideally the 2 repos should be made consistent on merged commits. Additional  changes also can be applied when they happen.

**Comment by jk-jeon** [comment]
>Also the implementations of policies in both the repos are complicated. Perhaps it can be simplified to be simple.

Do you have any idea on that?

**Comment by sirinath** [comment]
At the moment I am not sure. But there is an alternate simplified implementation here: https://github.com/abolz/Drachennest/blob/master/src/dragonbox.cc

**Comment by sirinath** [comment]
Some times it is difficult to track the code when related code appear in many places like:
- https://github.com/jk-jeon/fp/tree/master/include/jkj/fp/to_chars and https://github.com/jk-jeon/fp/tree/master/source/to_chars
- https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/detail/policy.h and https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/policy.h
- https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/dragonbox.h#L41 and https://github.com/jk-jeon/fp/blob/master/include/jkj/fp/detail/div.h
- etc.
